# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../../../node_modules/@react-native-community/cli-platform-ios/native_modules.rb'

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Prayer' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'PrayerTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      next unless target.name == 'RCT-Folly'

      target.build_configurations.each do |build_configuration|
        %w[OTHER_CFLAGS OTHER_CPLUSPLUSFLAGS].each do |setting|
          flags = build_configuration.build_settings[setting]
          flags = ['$(inherited)'] if flags.nil?
          flags = [flags] if flags.is_a?(String)

          unless flags.any? { |flag| flag.include?('FOLLY_HAVE_CLOCK_GETTIME') }
            flags << '-DFOLLY_HAVE_CLOCK_GETTIME=1'
          end

          build_configuration.build_settings[setting] = flags
        end
      end
    end

    folly_time_header = installer.sandbox.root + 'RCT-Folly/folly/portability/Time.h'
    if folly_time_header.exist?
      contents = folly_time_header.read
      guard_snippet = '__IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_10_0'

      unless contents.include?(guard_snippet)
        search = '#if !FOLLY_HAVE_CLOCK_GETTIME && (defined(__MACH__) || defined(_WIN32))'
        replacement = <<~'EOS'
#if !FOLLY_HAVE_CLOCK_GETTIME && (defined(__MACH__) || defined(_WIN32)) && \
    !(defined(TARGET_OS_IPHONE) && TARGET_OS_IPHONE &&                     \
      defined(__IPHONE_OS_VERSION_MIN_REQUIRED) &&                         \
      __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_10_0)
EOS

        if contents.include?(search)
          folly_time_header.open('w') { |f| f.write(contents.sub(search, replacement)) }
        end
      end
    end
  end
end
